# Generated by Django 4.2.7 on 2024-01-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_customer_usser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='catagofavry',
        ),
    ]
