# Generated by Django 4.2.7 on 2024-01-17 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_order_customer_delete_customer'),
        ('accounts', '0003_remove_customer_catagofavry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='catagofavry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
