# Generated by Django 4.2.7 on 2024-01-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
