# Generated by Django 4.2.7 on 2024-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='session_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
