# Generated by Django 4.2.7 on 2024-03-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='session_id',
            new_name='device',
        ),
    ]
