# Generated by Django 4.2.7 on 2024-03-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_gust'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gust',
        ),
    ]
