# Generated by Django 4.2.6 on 2023-12-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('v', 'versatsse'), ('d', 'dior')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
