# Generated by Django 4.2.6 on 2023-12-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genders',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
