# Generated by Django 4.2.7 on 2024-01-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
