# Generated by Django 4.2.7 on 2024-01-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_customer_email_remove_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
    ]
