# Generated by Django 4.2.7 on 2024-01-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_customer_firstname_remove_customer_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
