# Generated by Django 4.2.7 on 2024-01-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_order_customer_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
