# Generated by Django 4.2.7 on 2024-01-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
