# Generated by Django 4.2.7 on 2024-01-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_cartitem_cart_id_cartitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_id',
        ),
    ]
