# Generated by Django 4.2.7 on 2024-03-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_gust_cartitem_gust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='gust',
            name='catagofavry',
        ),
        migrations.RemoveField(
            model_name='gust',
            name='name',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='gust',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.gust'),
        ),
    ]
