# Generated by Django 4.2.7 on 2024-03-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_cartitem_session_id_remove_gust_catagofavry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gust',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
