# Generated by Django 4.2.7 on 2024-03-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_gust_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='gust',
            new_name='gu',
        ),
    ]
