# Generated by Django 4.2.7 on 2024-03-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_gust_cartitem_gu'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        
    ]
