# Generated by Django 4.2.7 on 2024-03-16 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_order_iteams_order_user'),
    ]

    operations = [
       
      
        migrations.AddField(
            model_name='cartitem',
            name='session_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
