# Generated by Django 4.2.7 on 2024-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_cartitem_id_cartitem_cart_id_and_more'),
    ]

    operations = [
    
    ]
