# Generated by Django 4.2.7 on 2024-03-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_cartitem_cart_id_remove_cartitem_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='iteams',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
