# Generated by Django 4.2.7 on 2024-03-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zones',
            field=models.CharField(choices=[('c', 'القاهرة'), ('g', 'الجيزة'), ('a', 'العصيد'), ('d', 'الدلتا'), ('b', 'الغردقة-البحر-الاحمر'), ('s', 'شرم-الشيخ-جنوب سيناء'), ('n', 'المدن-الجديدة'), ('m', 'مدينة-بدر'), ('x', 'اسكندرية'), ('xs', 'اطراف-الاسكندرية'), ('q', 'القناة')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
