# Generated by Django 4.2.7 on 2024-04-07 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_order_email_order_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
