# Generated by Django 4.2.7 on 2024-04-07 02:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0035_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('zones', models.CharField(choices=[('c', 'القاهرة'), ('g', 'الجيزة'), ('a', 'العصيد'), ('d', 'الدلتا'), ('b', 'الغردقة-البحر-الاحمر'), ('s', 'شرم-الشيخ-جنوب سيناء'), ('n', 'المدن-الجديدة'), ('m', 'مدينة-بدر'), ('x', 'اسكندرية'), ('xs', 'اطراف-الاسكندرية'), ('q', 'القناة')], max_length=2)),
                ('adress', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
