# Generated by Django 4.2.7 on 2024-04-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
