# Generated by Django 4.2.7 on 2024-04-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_order_date_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iteams',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.cartitem'),
            preserve_default=False,
        ),
    ]
