# Generated by Django 4.2.7 on 2024-04-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_order_iteams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='iteams',
        ),
    ]
