# Generated by Django 4.2.7 on 2024-05-05 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_order_iteams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='session_id',
            new_name='session',
        ),
    ]
