# Generated by Django 4.2.7 on 2024-05-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_rename_session_id_cartitem_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='iteams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cartitem'),
        ),
    ]
