# Generated by Django 4.2.7 on 2024-05-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_order_iteams'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
