# Generated by Django 4.2.7 on 2024-05-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order'),
        ),
        migrations.AlterField(
            model_name='test',
            name='iteams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cartitem'),
        ),
    ]
