# Generated by Django 4.2.7 on 2024-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_test_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
