# Generated by Django 4.2.7 on 2024-05-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_order_status_test_status'),
    ]

   