# Generated by Django 4.2.7 on 2024-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_test_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='info',
            field=models.CharField(max_length=250),
        ),
    ]
