# Generated by Django 4.2.7 on 2024-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_remove_test_info'),
    ]

   
