# Generated by Django 4.2.7 on 2024-05-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_delete_test_alter_order_iteams'),
    ]

 