# Generated by Django 4.2.7 on 2024-05-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_delete_test_alter_product_genders_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='uploads/product'),
        ),
    ]
