# Generated by Django 4.2.7 on 2024-05-16 01:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_delete_test_alter_product_image'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[4578, 5723], upload_to='uploads/product'),
        ),
    ]
