# Generated by Django 4.2.7 on 2024-06-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_inc_delete_test_alter_productattribute_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='home.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
