# Generated by Django 4.2.7 on 2024-06-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_productvariation_remove_productattribute_product_and_more'),
    ]

    operations = [
        
    ]
