# Generated by Django 4.2.7 on 2024-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_delete_test_alter_cartitem_product_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
