# Generated by Django 4.2.7 on 2024-06-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_delete_test_alter_cartitem_product'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
