# Generated by Django 4.2.7 on 2024-06-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0074_delete_test_productvariation_discount'),
    ]

    operations = [
      
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='ProductVariation',
        ),
    ]
