# Generated by Django 4.2.7 on 2024-06-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_delete_test_rename_product_cartitem_productvariation'),
    ]

    operations = [
        
    ]
