# Generated by Django 4.2.7 on 2024-06-08 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_delete_test_remove_productvariation_product_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='product',
            name='ProductVariation',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='home.product'),
            preserve_default=False,
        ),
    ]
