# Generated by Django 4.2.7 on 2024-06-08 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0079_delete_test_remove_product_productvariation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='checked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkedd', models.CharField(max_length=50)),
            ],
        ),
       
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('v', 'versatsse'), ('d', 'dior'), ('M', 'Mancera')], max_length=1),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='ava',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.checked'),
        ),
    ]
