# Generated by Django 4.2.7 on 2024-06-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_checked_delete_test_alter_product_brand_and_more'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='product',
            name='ava',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='genders',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='brand',
            field=models.CharField(choices=[('v', 'versatsse'), ('d', 'dior'), ('M', 'Mancera')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='catagory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.catagory'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='genders',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unisex')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
