# Generated by Django 4.2.7 on 2024-06-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0082_delete_test_alter_productvariation_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
       
        migrations.AlterField(
            model_name='productvariation',
            name='kind',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.kind'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.size'),
        ),
    ]
