# Generated by Django 4.2.7 on 2024-06-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0084_rename_catagory_category_delete_test_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='order',
            name='phone2',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
